import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/common";

const myFont = localFont({
    src: [
        {
            path: "../../public/assets/fonts/Gilroy-Light.ttf",
            weight: "300",
            style: "normal",
        },
        {
            path: "../../public/assets/fonts/Gilroy-Regular.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/assets/fonts/Gilroy-Medium.ttf",
            weight: "500",
            style: "normal",
        },
        {
            path: "../../public/assets/fonts/Gilroy-Bold.ttf",
            weight: "700",
            style: "normal",
        },
        {
            path: "../../public/assets/fonts/Gilroy-Heavy.ttf",
            weight: "800",
            style: "normal",
        },
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={myFont.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
